DESHIMA: merge_to_dfits.MergeToDfits Class Reference
merge_to_dfits.MergeToDfits Class Reference
Public Member Functions
def __init__ (self, ddbfits, dfitsdict, obsinst, antennalog, rout_data, weatherlog=None, cabinlog=None)
def dfits (self)
def obsinfo (self)
def antenna (self)
def readout (self)
def kidsinfo (self)
def weather (self)
def cabin_t (self)
Public Attributes
ddbfits
dfitsdict
obsinst
antennalog
rout_data
weatherlog
cabinlog
pixelid
db_ret
dfits_dict
ant_time
cabin_db
kidsinfo_hdus
Detailed Description
Read logging data of ASTE and merge them into a FITS object
Args.:
    ddbfits    (str): File name of the DESHIMA Database FITS.
    dfitsdict  (str): File name of the DFITS Dictionay file (yaml).
    obsinst    (str): File name of the Observation Instruction.
    antennalog (str): File name of the Antennalogging.
    rout_data  (str): File name of the Readout Data (FITS).
    weatherlog (str): File name of the Weatherlogging.
                      Default is None.
    cabinlog   (str): File name of the cabin temperature log database.
                      Default is None.
Example:
    "ddbfits"   : DDB_20180208.fits
    "dfitsdict" : dfits_dict.yaml
    "obsinst"   : 20171024012916.obs
    "antennalog": 20171024012916.ant
    "rout_data" : reduced_20171024012916.fits
    "weatherlog": 20171024012916.wea
    "cabinlog"  : cabin.db
    Get HDUList of DFITS:
    >>> mtd = MergeToDfits(
            ddbfits=ddbfits,
            dfitsdict=dfitsdict,
            obsinst=obsinst,
            antennalog=antennalog,
            rout_data=rout_data
        )
    >>> dfits = mtd.dfits
    >>> dfits.indo()
    Filename: (No file associated with this HDUList)
    No.    Name         Type      Cards   Dimensions   Format
    0  PRIMARY     PrimaryHDU       4   ()
    1  OBSINFO     BinTableHDU     56   1R x 12C   ['K', 'D', 'D', 'D', 'D', 'D', 'D', '63K', '63K', '63K', '63D', '63D']
    2  ANTENNA     BinTableHDU     32   3854R x 8C   ['26A', '4A', 'D', 'D', 'D', 'D', 'D', 'D']
    3  KIDSINFO    BinTableHDU     29   63R x 8C   ['I', 'I', 'E', '2E', '2E', '2E', '2E', '2E']
    4  READOUT     BinTableHDU     23   29234R x 5C   ['26A', 'K', '63D', '63D', '63D']
    Get each HDU:
    >>> mtd = MergeToDfits(
            ddbfits=ddbfits,
            dfitsdict=dfitsdict,
            obsinst=obsinst,
            antennalog=antennalog,
            rout_data=rout_data,
            weatherlog=weatherlog,
            cabinlog=cabindb
        )
    >>> obsinfo = mtd.obsinfo
    >>> antenna = mtd.antenna
    >>> readout = mtd.readout
    >>> weather = mtd.weather
Definition at line 31 of file merge_to_dfits.py.
Constructor & Destructor Documentation
__init__()
def merge_to_dfits.MergeToDfits.__init__ (self, ddbfits, dfitsdict, obsinst, antennalog, rout_data, weatherlog = None, cabinlog = None)
Definition at line 87 of file merge_to_dfits.py.
Member Function Documentation
antenna()
def merge_to_dfits.MergeToDfits.antenna (self)
HDU of 'ANTENNA'
Definition at line 173 of file merge_to_dfits.py.
References merge_to_dfits.MergeToDfits.ant_time, merge_to_dfits.MergeToDfits.antennalog, and merge_to_dfits.MergeToDfits.dfits_dict.
Referenced by merge_to_dfits.MergeToDfits.dfits().
cabin_t()
def merge_to_dfits.MergeToDfits.cabin_t (self)
HDU of 'CABIN_T'
Definition at line 268 of file merge_to_dfits.py.
References merge_to_dfits.MergeToDfits.cabin_db, merge_to_dfits.MergeToDfits.cabinlog, merge_to_dfits.MergeToDfits.db_ret, and merge_to_dfits.MergeToDfits.dfits_dict.
Referenced by merge_to_dfits.MergeToDfits.dfits().
dfits()
def merge_to_dfits.MergeToDfits.dfits (self)
HDU list of DFITS(Merge to DFITS)
Definition at line 120 of file merge_to_dfits.py.
References merge_to_dfits.MergeToDfits.antenna(), merge_to_dfits.MergeToDfits.cabin_t(), merge_to_dfits.MergeToDfits.cabinlog, merge_to_dfits.MergeToDfits.kidsinfo(), merge_to_dfits.MergeToDfits.obsinfo(), merge_to_dfits.MergeToDfits.readout(), merge_to_dfits.MergeToDfits.weather(), and merge_to_dfits.MergeToDfits.weatherlog.
kidsinfo()
def merge_to_dfits.MergeToDfits.kidsinfo (self)
HDU of 'KIDSINFO'
Definition at line 241 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.dfits().
obsinfo()
def merge_to_dfits.MergeToDfits.obsinfo (self)
HDU of 'OBSINFO'
Definition at line 135 of file merge_to_dfits.py.
References merge_to_dfits.MergeToDfits.ant_time, merge_to_dfits.MergeToDfits.ddbfits, merge_to_dfits.MergeToDfits.dfits_dict, merge_to_dfits.MergeToDfits.obsinst, and merge_to_dfits.MergeToDfits.pixelid.
Referenced by merge_to_dfits.MergeToDfits.dfits().
readout()
def merge_to_dfits.MergeToDfits.readout (self)
HDU of 'READOUT'
Definition at line 197 of file merge_to_dfits.py.
References merge_to_dfits.MergeToDfits.cabin_db, merge_to_dfits.MergeToDfits.db_ret, merge_to_dfits.MergeToDfits.ddbfits, merge_to_dfits.MergeToDfits.dfits_dict, merge_to_dfits.MergeToDfits.pixelid, merge_to_dfits.MergeToDfits.rout_data, and merge_to_dfits.MergeToDfits.weatherlog.
Referenced by merge_to_dfits.MergeToDfits.dfits().
weather()
def merge_to_dfits.MergeToDfits.weather (self)
HDU of 'WEATHER'
Definition at line 247 of file merge_to_dfits.py.
References merge_to_dfits.MergeToDfits.dfits_dict, and merge_to_dfits.MergeToDfits.weatherlog.
Referenced by merge_to_dfits.MergeToDfits.dfits().
Member Data Documentation
ant_time
merge_to_dfits.MergeToDfits.ant_time
Definition at line 111 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.antenna(), and merge_to_dfits.MergeToDfits.obsinfo().
antennalog
merge_to_dfits.MergeToDfits.antennalog
Definition at line 92 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.antenna().
cabin_db
merge_to_dfits.MergeToDfits.cabin_db
Definition at line 115 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.cabin_t(), and merge_to_dfits.MergeToDfits.readout().
cabinlog
merge_to_dfits.MergeToDfits.cabinlog
Definition at line 99 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.cabin_t(), and merge_to_dfits.MergeToDfits.dfits().
db_ret
merge_to_dfits.MergeToDfits.db_ret
Definition at line 104 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.cabin_t(), and merge_to_dfits.MergeToDfits.readout().
ddbfits
merge_to_dfits.MergeToDfits.ddbfits
Definition at line 89 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.obsinfo(), and merge_to_dfits.MergeToDfits.readout().
dfits_dict
merge_to_dfits.MergeToDfits.dfits_dict
Definition at line 107 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.antenna(), merge_to_dfits.MergeToDfits.cabin_t(), merge_to_dfits.MergeToDfits.obsinfo(), merge_to_dfits.MergeToDfits.readout(), and merge_to_dfits.MergeToDfits.weather().
dfitsdict
merge_to_dfits.MergeToDfits.dfitsdict
Definition at line 90 of file merge_to_dfits.py.
kidsinfo_hdus
merge_to_dfits.MergeToDfits.kidsinfo_hdus
Definition at line 243 of file merge_to_dfits.py.
obsinst
merge_to_dfits.MergeToDfits.obsinst
Definition at line 91 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.obsinfo().
pixelid
merge_to_dfits.MergeToDfits.pixelid
Definition at line 103 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.obsinfo(), and merge_to_dfits.MergeToDfits.readout().
rout_data
merge_to_dfits.MergeToDfits.rout_data
Definition at line 93 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.readout().
weatherlog
merge_to_dfits.MergeToDfits.weatherlog
Definition at line 95 of file merge_to_dfits.py.
Referenced by merge_to_dfits.MergeToDfits.dfits(), merge_to_dfits.MergeToDfits.readout(), and merge_to_dfits.MergeToDfits.weather().
The documentation for this class was generated from the following file:
merge_to_dfits.py