DESHIMA: test_dmerge.DmergeTestDrive Class Reference
test_dmerge.DmergeTestDrive Class Reference
Public Member Functions
def setUp (self)
def load_data (self)
def test_SweepData (self)
def test_FixedData (self)
def test_FixedFitData (self)
def test_Expr_with_args (self)
def test_divide_data (self)
def test_make_divided_data (self)
def test_kids_with_both_blinds (self)
def test_read_kidslist (self)
def test_load_localsweep (self)
def test_fit_sweep (self)
def test_calc_resonance_params (self)
def test_parallel_calc_resonance_params (self)
def test_rewind (self)
def test_make_reduced_fits (self)
def test_mergefits (self)
def test_plot_sweep (self)
def test_parallel_plot_sweep (self)
Detailed Description
dmerge.pyモジュールの単体テスト
Definition at line 31 of file test_dmerge.py.
Member Function Documentation
load_data()
def test_dmerge.DmergeTestDrive.load_data (self)
SweepデータやTODを読み込む
Definition at line 36 of file test_dmerge.py.
Referenced by test_dmerge.DmergeTestDrive.test_divide_data(), and test_dmerge.DmergeTestDrive.test_fit_sweep().
setUp()
def test_dmerge.DmergeTestDrive.setUp (self)
Definition at line 33 of file test_dmerge.py.
test_calc_resonance_params()
def test_dmerge.DmergeTestDrive.test_calc_resonance_params (self)
calc_resonance_params.pyスクリプトの試験
Definition at line 300 of file test_dmerge.py.
test_divide_data()
def test_dmerge.DmergeTestDrive.test_divide_data (self)
KID毎にSweepデータやTODを分割して辞書に格納する機能の試験
機能
----
divide_data()関数はsweep_data, kidlist, todを受け取り、
それらをKID毎に分割して辞書に格納する。
その辞書を適当に分割してファイルに保存すれば、
並列処理に利用できる。
Definition at line 178 of file test_dmerge.py.
References dmerge.divide_data(), and test_dmerge.DmergeTestDrive.load_data().
test_Expr_with_args()
def test_dmerge.DmergeTestDrive.test_Expr_with_args (self)
Expr_with_argsの仕組みを調べる
Definition at line 165 of file test_dmerge.py.
test_fit_sweep()
def test_dmerge.DmergeTestDrive.test_fit_sweep (self)
1つのKIDのSweepデータをフィットする試験
Definition at line 253 of file test_dmerge.py.
References dmerge.divide_data(), dmerge.find_peaks(), dmerge.fit_onepeak(), and test_dmerge.DmergeTestDrive.load_data().
test_FixedData()
def test_dmerge.DmergeTestDrive.test_FixedData (self)
FixedDataクラスのテスト
Definition at line 64 of file test_dmerge.py.
References dmerge.calibrate_with_blind_tones().
test_FixedFitData()
def test_dmerge.DmergeTestDrive.test_FixedFitData (self)
単純にしたFixedFitDataのテスト
Definition at line 110 of file test_dmerge.py.
References dmerge.calibrate_with_blind_tones(), and dmerge.gaolinbg_rewind().
test_kids_with_both_blinds()
def test_dmerge.DmergeTestDrive.test_kids_with_both_blinds (self)
kids_with_both_blinds()関数のテストと単機能の関数のテスト
Definition at line 216 of file test_dmerge.py.
References dmerge.find_nearest_blind_tones(), dmerge_deprecated.kids_with_both_blinds(), and dmerge.load_kidslist().
test_load_localsweep()
def test_dmerge.DmergeTestDrive.test_load_localsweep (self)
ローカルsweepデータをロードするテスト(ロード結果が古い関数と同じであることを確認する)
Definition at line 236 of file test_dmerge.py.
References dmerge.load_kidslist(), dmerge.load_localsweep(), and dmerge_deprecated.read_localsweep().
test_make_divided_data()
def test_dmerge.DmergeTestDrive.test_make_divided_data (self)
make_divided_data.pyスクリプトの試験
Definition at line 203 of file test_dmerge.py.
test_make_reduced_fits()
def test_dmerge.DmergeTestDrive.test_make_reduced_fits (self)
make_reduced_fits.pyスクリプトの試験
方法
----
make_reduced_fits.pyで生成されるreduced.fitsファイルと旧プログラムで生成されるものと中身を比較する。
Definition at line 425 of file test_dmerge.py.
test_mergefits()
def test_dmerge.DmergeTestDrive.test_mergefits (self)
MergeFitsのテスト
TODO:
(v) とりあえず、reduced.fitsをそのままマージできるかどうか、試してみる。
(v) マージの結果が旧プログラムと同じことを確認する。
Definition at line 526 of file test_dmerge.py.
test_parallel_calc_resonance_params()
def test_dmerge.DmergeTestDrive.test_parallel_calc_resonance_params (self)
calc_resonance_params.pyスクリプトを用いた並列処理の試験
Definition at line 318 of file test_dmerge.py.
test_parallel_plot_sweep()
def test_dmerge.DmergeTestDrive.test_parallel_plot_sweep (self)
plot_sweep.pyスクリプトを用いた並列処理の試験
Definition at line 586 of file test_dmerge.py.
test_plot_sweep()
def test_dmerge.DmergeTestDrive.test_plot_sweep (self)
plot_sweep()関数を用いて1つのKIDについてプロットを作成するテスト
Definition at line 576 of file test_dmerge.py.
test_read_kidslist()
def test_dmerge.DmergeTestDrive.test_read_kidslist (self)
新しいread_kidslist()関数をテストする
Definition at line 224 of file test_dmerge.py.
References dmerge.load_kidslist(), and dmerge_deprecated.read_kidslist().
test_rewind()
def test_dmerge.DmergeTestDrive.test_rewind (self)
rewind()関数の試験
方法
----
rewind()関数を用いてキャリア周波数と共振周波数の位相を計算する。
reduced_*.fitsに保存されている位相と比べる。
Definition at line 340 of file test_dmerge.py.
References dmerge.find_peaks(), dmerge.fit_onepeak(), dmerge.gaolinbg_function(), and dmerge.gaolinbg_rewind().
test_SweepData()
def test_dmerge.DmergeTestDrive.test_SweepData (self)
SweepDataクラスのテスト
Definition at line 43 of file test_dmerge.py.
The documentation for this class was generated from the following file:
test_dmerge.py