DESHIMA: dmerge Namespace Reference
dmerge Namespace Reference
Classes
class SweepData
class FixedData
class FixedFitData
class TODs
Functions
def divide_data (kidslist, localsweep, tods)
def find_nearest_blind_tones (kidslist)
def load_kidslist (filename)
def load_localsweep (filename, framelen)
def fit_onepeak (sweepdata, peaks, nfwhm=5)
def search_peak (sweepdata, peaks)
def find_peaks (freq, ampl, fc, smooth=None, threshold=None, minq=10000, maxratio=0.5)
def oddify (n)
def fitLorentzian (freq, ampl, f0, q0)
def adjust_fitrange (nfwhm, ndata, nparams, peakparams, factor=1)
def readout_dict ()
def kids_dict ()
def rebin_array (inarray, rebin)
def find_glitch (yss, baseline_thresh=6.0, glitch_thresh=5.0, clusterize_thresh=2, offset=0, opt_diff2=True, smrange=1, returnval=False)
def calibrate_with_blind_tones (signal, blind_left, blind_right)
def interpolate_bad (ys, bad)
def createBinTableHDU (data_dict)
def addHeaderComments (hdr, key, com)
def f_Lorentzian (params, freq, data=None)
def gaolinbg_guess (sweepdata, peaks)
def gaolinbg_rewind (x, y, arga, absa, tau, fr, Qr, Qc, phi0, c)
def gaolinbg_expression ()
def gaolinbg_bg_expression ()
def gaolinbg_function ()
def gaolinbg_bg_function ()
def gaolinbg_param_gradient_function ()
def complex_to_cartesian2darray (x)
def cartesian2darray_to_complex (x)
def power_spectrum_density (data, dt, ndivide=1, window=scipy.signal.hanning, overwrap_half=False)
Detailed Description
DESHIMA解析プログラム
File name: dmerge.py
Python 3.7
(C) 2021 内藤システムズ
Function Documentation
addHeaderComments()
def dmerge.addHeaderComments (hdr, key, com)
Add Comments to Header
Definition at line 760 of file dmerge.py.
Referenced by createBinTableHDU().
adjust_fitrange()
def dmerge.adjust_fitrange (nfwhm, ndata, nparams, peakparams, factor = 1)
Adjust fit range to make sure :math:`N_{free} \geq nparam`
引数
----
float   nfwhm: minimum fit length in unit of FWHM
integer ndata: length of data
integer nparams: number of parameter
dict    peakparams: peak information
integer factor
戻り値
------
tuple (rbegin, rend) フィット範囲の始まりと終わりのインデックス
factorについて
--------------
Specify 2 as 'factor' if you fit complex variable(as 2d-vector).
利用するピークパラメタ
----------------------
 - f0ind: a integer, index of peak center
 - dl   : a integer, index count to reach the left half-maximum
 - dr   : a integer, index count to reach the right half-maximum
Definition at line 480 of file dmerge.py.
Referenced by fit_onepeak().
calibrate_with_blind_tones()
def dmerge.calibrate_with_blind_tones (signal, blind_left, blind_right)
do blind tone calibration.
引数
----
signal     : signal tone TOD.
blind_left : left blind tone TOD.
blind_right: right blind tone TOD.
戻り値
------
a 1-D array of complex value (calibrated IQ)
詳細
----
each parameter is either a FixedData or a tuple (freq, IQ)
where freq is a frequency [Hz],
IQ is a 1-D array of IQ data as complex value.
Definition at line 693 of file dmerge.py.
Referenced by make_reduced_fits.make_reduced_fits(), test_dmerge.DmergeTestDrive.test_FixedData(), and test_dmerge.DmergeTestDrive.test_FixedFitData().
cartesian2darray_to_complex()
def dmerge.cartesian2darray_to_complex (x)
Definition at line 875 of file dmerge.py.
complex_to_cartesian2darray()
def dmerge.complex_to_cartesian2darray (x)
Definition at line 870 of file dmerge.py.
Referenced by fit_onepeak().
createBinTableHDU()
def dmerge.createBinTableHDU (data_dict)
Definition at line 742 of file dmerge.py.
References addHeaderComments().
Referenced by make_reduced_fits.make_reduced_fits().
divide_data()
def dmerge.divide_data (kidslist, localsweep, tods)
KID毎にSweepデータやTODを分割して辞書に格納する
引数
----
list dmerge.load_kidslist()関数で得られるタプル(info, kid_bins, blind_bins, powers)
list SweepDataオブジェクトのリスト
TODs TODsオブジェクト
戻り値
------
リスト
Definition at line 22 of file dmerge.py.
References find_nearest_blind_tones().
Referenced by test_dmerge.DmergeTestDrive.test_divide_data(), and test_dmerge.DmergeTestDrive.test_fit_sweep().
f_Lorentzian()
def dmerge.f_Lorentzian (params, freq, data = None)
Lorengzianモデル関数
mkid_data/peak_search.pyで使われている関数と同じ。
引数のdataが指定された場合はモデル関数の計算値とdataの差を返す。
引数
----
numpy.Parameters
numpy.array 周波数
numpy.array amplitude
戻り値
------
モデルの計算値|計算値とdataの差
Definition at line 764 of file dmerge.py.
find_glitch()
def dmerge.find_glitch (yss, baseline_thresh = 6.0, glitch_thresh = 5.0, clusterize_thresh = 2, offset = 0, opt_diff2 = True, smrange = 1, returnval = False)
find glitches common to `yss`, assuming glitch exists at the same
time of all data in `yss`. Too close glitches or broad glitch are
treated as one glitch.
引数
----
yss              : an array of 1-D arrays of data to deglitch
baseline_thresh  : threshold to decide baseline
glitch_thresh    : threshold to decide as glitch
clusterize_thresh: if gap between glitches are less than or equal to this, treat them as one glitch.
offset           : an integer offset added to returned bad array
opt_diff2        : bool to select whether to use 2nd derivative for glitch identification
smrange          : an integer to set range of rolling mean (used for glitch identification based on std)
returnval        : bool to choose whether to return threshold value or not
戻り値(returnvalの値によって変化する)
-------------------------------------
an 1-D array of boolean, that can be used as index of ys (elements of yss).
(option) threshold value for glitch identification (return when returnval=True)
Definition at line 587 of file dmerge.py.
Referenced by make_reduced_fits.make_reduced_fits().
find_nearest_blind_tones()
def dmerge.find_nearest_blind_tones (kidslist)
 KID信号の左右にある最も近いblind信号を探す
引数
----
kidslist(dmerge.read_kidslist()関数の戻り値)
戻り値
------
list [[KID信号, 左blind tone, 右blind tone], ...]
戻り値の例
----------
[[-196483 -201203 -192949]
 [-189634 -192949 -184695]
 [-188948 -192949 -184695]
...
 [ 154774  153170  161962]
 [ 158692  153170  161962]
 [ 169653  161962  171230]]
詳細
----
この関数は引数に与えられたkidslistに含まれるkidsとblindsを利用する。
kidsとblindsを組み合わせて各kid信号の両側にある最も近いblind信号を探す。
見つかった左右のblind信号とkid信号をリストにまとめて返す。戻り値はリストの入れ子構造となる。
blind信号が見つからない場合はNoneが格納される。
戻り値はkidのbin番号で昇順になっている。
この関数はbbsweeplib.TODcalibに定義されていたkids_with_both_blinds()関数を単機能にしたもの。
探索の方法
----------
kid信号とblind信号を合わせたリストを作成する。このリストはbin番号で昇順に並べ替えられている。
あるkid信号のindexを取得し、そこを起点に左右に探索する(indexを減少または増加させる)。起点は含まない。
見つかった信号のbin番号がblind信号のリストに含まれる場合は、それをそのkid信号のblind信号とする。
Definition at line 55 of file dmerge.py.
Referenced by divide_data(), and test_dmerge.DmergeTestDrive.test_kids_with_both_blinds().
find_peaks()
def dmerge.find_peaks (freq, ampl, fc, smooth = None, threshold = None, minq = 10000, maxratio = 0.5)
Search peaks in data.
引数
----
freq      周波数の配列
ampl      amplitudeの配列
fc        TODのキャリア周波数
smooth    平滑化のwindow長(正の整数)[オプション]
threshold ピークの判定基準[オプション]
minq      Qの最小値(ピークの良し悪しの判定に利用する)[オプション]
maxratio  (bg - d)/bgの最小値(ピークの良し悪しの判定に利用する)[オプション]
戻り値
------
list Lorentzianのフィット共にgaolinbgのパラメタの初期値を決定するのに必要なパラメタを辞書にまとめたリスト
Definition at line 323 of file dmerge.py.
References fitLorentzian(), and oddify().
Referenced by calc_resonance_params.calc_resonance_params(), test_dmerge.DmergeTestDrive.test_fit_sweep(), and test_dmerge.DmergeTestDrive.test_rewind().
fit_onepeak()
def dmerge.fit_onepeak (sweepdata, peaks, nfwhm = 5)
Sweepデータをgaolinbgでフィットする
引数
----
SweepData Sweepデータオブジェクト
list      find_peaks()関数で得られる各ピークのパラメタのリスト
integer   nfwhm
戻り値
------
MinimizerResult gaolinbgによるフィットの結果
slice           フィット範囲(インデックス)
Definition at line 227 of file dmerge.py.
References adjust_fitrange(), complex_to_cartesian2darray(), gaolinbg_function(), gaolinbg_guess(), and gaolinbg_param_gradient_function().
Referenced by calc_resonance_params.calc_resonance_params(), test_dmerge.DmergeTestDrive.test_fit_sweep(), and test_dmerge.DmergeTestDrive.test_rewind().
fitLorentzian()
def dmerge.fitLorentzian (freq, ampl, f0, q0)
Fit data with Lorentzian curve.
引数
----
freq a 1-D array of frequency
ampl a 1-D array of amplitude
f0   initial parameter for center frequency
q0   initial parameter for quality factor
戻り値
------
(fc, q, d, bg) フィットの結果をまとめたタプル
パラメタの説明
--------------
f : center frequency
q : quality factor
d : amplitude for Lorentzian curve
bg: constant background level
Definition at line 445 of file dmerge.py.
Referenced by find_peaks().
gaolinbg_bg_expression()
def dmerge.gaolinbg_bg_expression ()
Definition at line 822 of file dmerge.py.
Referenced by gaolinbg_bg_function().
gaolinbg_bg_function()
def dmerge.gaolinbg_bg_function ()
Definition at line 837 of file dmerge.py.
References gaolinbg_bg_expression().
Referenced by plot.plot().
gaolinbg_expression()
def dmerge.gaolinbg_expression ()
Definition at line 813 of file dmerge.py.
Referenced by gaolinbg_function(), and gaolinbg_param_gradient_function().
gaolinbg_function()
def dmerge.gaolinbg_function ()
Definition at line 831 of file dmerge.py.
References gaolinbg_expression().
Referenced by fit_onepeak(), make_reduced_fits.make_reduced_fits(), plot.plot(), and test_dmerge.DmergeTestDrive.test_rewind().
gaolinbg_guess()
def dmerge.gaolinbg_guess (sweepdata, peaks)
Definition at line 789 of file dmerge.py.
References search_peak().
Referenced by fit_onepeak().
gaolinbg_param_gradient_function()
def dmerge.gaolinbg_param_gradient_function ()
Definition at line 843 of file dmerge.py.
References gaolinbg_expression().
Referenced by fit_onepeak().
gaolinbg_rewind()
def dmerge.gaolinbg_rewind (x, y, arga, absa, tau, fr, Qr, Qc, phi0, c)
Definition at line 809 of file dmerge.py.
Referenced by make_reduced_fits.make_reduced_fits(), plot.plot(), test_dmerge.DmergeTestDrive.test_FixedFitData(), and test_dmerge.DmergeTestDrive.test_rewind().
interpolate_bad()
def dmerge.interpolate_bad (ys, bad)
Linear interpolate `ys` in region `bad`.
引数
----
ys : an 1-D array
bad: an 1-D array of boolean, with True indicating bad region in `ys`.
戻り値
------
an 1-D array, with bad region interpolated.
Definition at line 727 of file dmerge.py.
Referenced by make_reduced_fits.make_reduced_fits().
kids_dict()
def dmerge.kids_dict ()
Definition at line 555 of file dmerge.py.
Referenced by make_reduced_fits.make_reduced_fits().
load_kidslist()
def dmerge.load_kidslist (filename)
kids.listファイルを読み込みBIN番号やローカル発振器の周波数などを取得する
引数
----
kids.listファイルへのパス
戻り値
------
dict ローカル発振器の周波数とフレーム長を辞書にまとめたもの
list KID信号のBIN番号のリスト
list blind信号のBIN番号のリスト
dict BIN番号をキー(Int型)にしたpower(float型)の辞書
詳細
----
kids.listファイルの最初の2行はヘッダーとして処理する。
1行目はローカル発振器の周波数、2行目はフレーム長である信じて読み込む。
3行目以降は「#KIDs」か「#blinds」かBIN番号とpowerのペアが記されているものとする。
「#KIDs」があった場合はそれ以降のBIN番号はkid_bins変数のリストに追加する。
「#blinds」があった場合はそれ以降のBIN番号はblind_bins変数のリストに追加する。
bins変数はkid_binsリストへの参照かblind_binsリストへの参照かになる。
bins変数によってmode変数やフラグ変数による判定が必要なくなる。
読み込むkids.listファイルの形式
-------------------------------
#LO:5600.0000
#framelen:19
#KIDs
-196483 -75
-189634 -75
-188948 -75
    :
    :
154774  -75
158692  -78
169653  -78
#blinds
-232027 -75
-224371 -75
-216715 -75
    :
    :
注意
----
ファイルから読み取った1行(line)は必ずstrip()で処理しないと正しく読み込めない。
bins変数とnbin変数を混同しないように注意されたい。
bins変数はkid_binsリストかblind_binsリストへの参照であり、nbin変数はBIN番号を一時的に格納する変数である。
Definition at line 113 of file dmerge.py.
Referenced by test_dmerge.DmergeTestDrive.test_kids_with_both_blinds(), test_dmerge.DmergeTestDrive.test_load_localsweep(), and test_dmerge.DmergeTestDrive.test_read_kidslist().
load_localsweep()
def dmerge.load_localsweep (filename, framelen)
ローカルsweepデータを読み込みBIN番号とSweepDataオブジェクトを対応づけた辞書として返す
引数
----
string  ローカルsweepファイルへのパス
integer フレーム長
戻り値
------
dict BIN番号とSweepDataオブジェクト対応づけた辞書
説明
----
元のプログラムではread_localsweep()関数と_read_sweep()関数に分かれていた処理を一緒にした。
read_localsweep()関数ではOrderedDict()を用いてSweepDataをBIN番号順に並べ替えていたが、
この後の計算や処理でBIN番号順に並んでいる必要がないので、単純な辞書にSweepDataを格納することとした。
並べ替えなどの処理を省いた。
またSweepDataの辞書を作る際に辞書包括表記を用いた。
参考文献
--------
spaceKIDS Readout System Manula(SK-SRON-018-V0.3) page.7
上記のページにローカルsweepデータの読み方と各種計算方法が記されている。
Definition at line 191 of file dmerge.py.
Referenced by test_dmerge.DmergeTestDrive.test_load_localsweep().
oddify()
def dmerge.oddify (n)
n/2を切り上げそれを2倍して1足し奇数にして返す
引数
----
integer
戻り値
------
integer 奇数
Definition at line 433 of file dmerge.py.
Referenced by find_peaks().
power_spectrum_density()
def dmerge.power_spectrum_density (data, dt, ndivide = 1, window = scipy.signal.hanning, overwrap_half = False)
Calculate power spectrum density of data.
引数
----
data         : input data
dt           : time between each data
ndivide      : do averaging(split data into ndivide, get psd of each, and average them)
overwrap_half: a boolean, split data to half-overwrapped regions
戻り値
------
(frequencies, psd)
Definition at line 880 of file dmerge.py.
Referenced by plot.plot().
readout_dict()
def dmerge.readout_dict ()
Definition at line 531 of file dmerge.py.
Referenced by make_reduced_fits.make_reduced_fits().
rebin_array()
def dmerge.rebin_array (inarray, rebin)
Definition at line 584 of file dmerge.py.
Referenced by make_reduced_fits.make_reduced_fits().
search_peak()
def dmerge.search_peak (sweepdata, peaks)
複数のピークが見つかった場合は中心周波数に一番近いピークを採用する
引数
----
SweepData Sweepデータオブジェクト
list      find_peaks()関数によって得られる各ピークのパラメタをまとめたリスト
戻り値
------
dict 選択されたピークのパラメタをまとめた辞書
Definition at line 303 of file dmerge.py.
Referenced by gaolinbg_guess().