DESHIMA: deshima Namespace Reference
deshima Namespace Reference
Classes
class KidFitResult
class MKIDDataException
Functions
def search_peaks (dat, fc, Q_search=100, S21min=1, plot=False)
def search_peak (dat, Q_search=100, S21min=1, plot=False)
def oddify (n)
def find_peaks (freq, ampl, fc, smooth=None, threshold=None, minq=10000, maxratio=0.5, mindist=5e-3, plot=False)
def fitLorentzian (freq, ampl, f0, q0)
def gaolinbg_guess (dat)
def adjust_fitrange (nfwhm, ndata, nparams, peakparams, factor=1)
def fit_onepeak_kai (dat, fc, errors=None, nfwhm=3, fitter='gaolinbg', Q_search=10000, plot=False)
def gaolinbg_expression ()
def gaolinbg_function ()
def gaolinbg_param_gradient_function ()
def hoge_fit (function, xs, ys, err=None, params=None, fitrange=None, silent=False, convert=None, **kws)
def fit_onepeak (dat, fc, errors=None, nfwhm=3, fitter='gaolinbg', Q_search=10000, plot=False)
def complex_to_cartesian2darray (x)
def cartesian2darray_to_complex (x)
def power_spectrum_density (data, dt, ndivide=1, doplot=False, window=scipy.signal.hanning, overwrap_half=False)
Detailed Description
DESHIMA解析プログラム
File name: deshima.py
Python 3.7
(C) 2021 内藤システムズ
Function Documentation
adjust_fitrange()
def deshima.adjust_fitrange (nfwhm, ndata, nparams, peakparams, factor = 1)
Adjust fit range to make sure :math:`N_{free} \geq nparam`
:param nfwhm: a float, minimum fit length in unit of FWHM
:param ndata: a integer, length of data
:param nparams: a integer, number of parameter
:param peakparams: a dict of peak information
:param factor: a integer
:Note: *specify 2* as **factor** if you fit complex variable (as 2d-vector)
**peakparams** are:
- **f0ind**: a integer, index of peak center
- **dl**: a integer, index count to reach the left half-maximum
- **dr**: a integer, index count to reach the right half-maximum
:return: (rbegin, rend)
- **rbegin** is a integer of fit range begin
- **rend** is a integer of fit range end
Definition at line 218 of file deshima.py.
Referenced by fit_onepeak(), and fit_onepeak_kai().
cartesian2darray_to_complex()
def deshima.cartesian2darray_to_complex (x)
Definition at line 496 of file deshima.py.
complex_to_cartesian2darray()
def deshima.complex_to_cartesian2darray (x)
Definition at line 491 of file deshima.py.
Referenced by hoge_fit().
find_peaks()
def deshima.find_peaks (freq, ampl, fc, smooth = None, threshold = None, minq = 10000, maxratio = 0.5, mindist = 5e-3, plot = False)
Search peaks in data.
Definition at line 39 of file deshima.py.
References fitLorentzian(), and oddify().
Referenced by search_peak(), and search_peaks().
fit_onepeak()
def deshima.fit_onepeak (dat, fc, errors = None, nfwhm = 3, fitter = 'gaolinbg', Q_search = 10000, plot = False)
Fit data with fitter.
:param data: sweep data to fit
:param fc: carrier frequency
:param error: error in data (data format depends on fitter)
:param nfwhm: fit range [FWHM]. if negative, use all data as fit range
:param fitter: fitter to use.
:param Q_search:
:param plot: 'all'/True/False
**fitter** supports:
- **gao**: a complex function from Jiansong Gao's D thesis (default)
- **gaolinbg**: a complex function from Jiansong Gao's D thesis
- **mazinrev**: a complex function from Ben Mazin's D thesis
- **blank**: a complex function only with cable delay effect or a Fitter object or a tuple (refer fitters.py)
Definition at line 381 of file deshima.py.
References adjust_fitrange(), gaolinbg_guess(), and search_peaks().
fit_onepeak_kai()
def deshima.fit_onepeak_kai (dat, fc, errors = None, nfwhm = 3, fitter = 'gaolinbg', Q_search = 10000, plot = False)
Fit data with fitter.
:param data: sweep data to fit
:param fc: carrier frequency
:param error: error in data (data format depends on fitter)
:param nfwhm: fit range [FWHM]. if negative, use all data as fit range
:param fitter: fitter to use.
:param Q_search:
:param plot: 'all'/True/False
Definition at line 266 of file deshima.py.
References adjust_fitrange(), gaolinbg_guess(), hoge_fit(), and search_peaks().
fitLorentzian()
def deshima.fitLorentzian (freq, ampl, f0, q0)
Fit data with lorenzian curve.
:param freq: a 1-D array of frequency
:param ampl: a 1-D array of amplitude
:param f0: initial parameter for center frequency
:param q0: initial parameter for quality factor
:return: (fc, q, d, bg)
- **fc**: fit of center frequency
- **q**: fit of quality factor
- **d**: fit of amplitude for Lorentzian curve
- **bg**: fit of constant background level
Definition at line 167 of file deshima.py.
Referenced by find_peaks().
gaolinbg_expression()
def deshima.gaolinbg_expression ()
Definition at line 305 of file deshima.py.
Referenced by gaolinbg_function(), gaolinbg_param_gradient_function(), and hoge_fit().
gaolinbg_function()
def deshima.gaolinbg_function ()
Definition at line 314 of file deshima.py.
References gaolinbg_expression().
Referenced by hoge_fit().
gaolinbg_guess()
def deshima.gaolinbg_guess (dat)
Definition at line 198 of file deshima.py.
References search_peak().
Referenced by fit_onepeak(), and fit_onepeak_kai().
gaolinbg_param_gradient_function()
def deshima.gaolinbg_param_gradient_function ()
Definition at line 320 of file deshima.py.
References gaolinbg_expression().
Referenced by hoge_fit().
hoge_fit()
def deshima.hoge_fit (function, xs, ys, err = None, params = None, fitrange = None, silent = False, convert = None, ** kws)
Definition at line 347 of file deshima.py.
References complex_to_cartesian2darray(), gaolinbg_expression(), gaolinbg_function(), and gaolinbg_param_gradient_function().
Referenced by fit_onepeak_kai().
oddify()
def deshima.oddify (n)
n/2を切り上げそれを2倍して1足す
Definition at line 35 of file deshima.py.
Referenced by find_peaks().
power_spectrum_density()
def deshima.power_spectrum_density (data, dt, ndivide = 1, doplot = False, window = scipy.signal.hanning, overwrap_half = False)
Calculate power spectrum density of data.
:param data:    input data
:param dt:      time between each data
:param ndivide: do averaging(split data into ndivide, get psd of each, and average them)
:param doplot:  plot how averaging works
:param overwrap_half:  a boolean, split data to half-overwrapped regions
:return: (frequencies, psd)
Definition at line 840 of file deshima.py.
search_peak()
def deshima.search_peak (dat, Q_search = 100, S21min = 1, plot = False)
複数のピークが見つかった場合は中心周波数に一番近いピークを採用する
Definition at line 20 of file deshima.py.
References find_peaks().
Referenced by gaolinbg_guess().
search_peaks()
def deshima.search_peaks (dat, fc, Q_search = 100, S21min = 1, plot = False)
Definition at line 17 of file deshima.py.
References find_peaks().
Referenced by fit_onepeak(), and fit_onepeak_kai().