DESHIMA: merge_function Namespace Reference
merge_function Namespace Reference
Classes
class CabinTempDB
Functions
def create_bintablehdu (hd)
def load_obsinst (obsinst)
def get_maskid_corresp (pixelid, ddb)
def Tlos_model (dx, p0, etaf, T0, Troom, Tamb)
def calibrate_to_power (pixelid, Troom, Tamb, rhdus, ddb)
def get_Troom (rhdus, cabin_db)
def convert_asciitime (asciitime, form_fitstime)
def convert_timestamp (timestamp)
Variables
string FORM_FITSTIME = '%Y-%m-%dT%H:%M:%S'
string FORM_FITSTIME_P = '%Y-%m-%dT%H:%M:%S.%f'
int CABIN_Q_MARGIN = 5*60
int DEFAULT_ROOM_T = 17. + 273.
int DEFAULT_AMB_T = 0. + 273.
Detailed Description
merge_to_dfits.py: Read logging data and merge them into a FITS object
 Author : Tetsutaro Ueda, Junya Suzuki, Kenichi Karatsu, Tatsuya Takekoshi
 Created: 2017/11/02
 Revision History:
     2018/02/08 - KK - rewrite using class.
     2018/06/08 - TT - apply new calibration method.
     2021         NAITO systems modfied.
Function Documentation
calibrate_to_power()
def merge_function.calibrate_to_power (pixelid, Troom, Tamb, rhdus, ddb)
Definition at line 148 of file merge_function.py.
References Tlos_model().
convert_asciitime()
def merge_function.convert_asciitime (asciitime, form_fitstime)
Ascii time
Definition at line 206 of file merge_function.py.
convert_timestamp()
def merge_function.convert_timestamp (timestamp)
Timestamp
Definition at line 212 of file merge_function.py.
Referenced by get_Troom().
create_bintablehdu()
def merge_function.create_bintablehdu (hd)
Create Binary Table HDU from 'hdu_dict'
Definition at line 64 of file merge_function.py.
get_maskid_corresp()
def merge_function.get_maskid_corresp (pixelid, ddb)
Get Correspondance of 'master' and 'kid'
Definition at line 108 of file merge_function.py.
get_Troom()
def merge_function.get_Troom (rhdus, cabin_db)
Get Troom from cabin temperature database
Definition at line 171 of file merge_function.py.
References convert_timestamp().
load_obsinst()
def merge_function.load_obsinst (obsinst)
Get data for 'OBSINFO'
Definition at line 82 of file merge_function.py.
Tlos_model()
def merge_function.Tlos_model (dx, p0, etaf, T0, Troom, Tamb)
Calibrate 'amplitude' and 'phase' to 'power'
Definition at line 144 of file merge_function.py.
Referenced by calibrate_to_power().
Variable Documentation
CABIN_Q_MARGIN
int merge_function.CABIN_Q_MARGIN = 5*60
Definition at line 40 of file merge_function.py.
DEFAULT_AMB_T
int merge_function.DEFAULT_AMB_T = 0. + 273.
Definition at line 42 of file merge_function.py.
DEFAULT_ROOM_T
int merge_function.DEFAULT_ROOM_T = 17. + 273.
Definition at line 41 of file merge_function.py.
FORM_FITSTIME
string merge_function.FORM_FITSTIME = '%Y-%m-%dT%H:%M:%S'
Definition at line 37 of file merge_function.py.
FORM_FITSTIME_P
string merge_function.FORM_FITSTIME_P = '%Y-%m-%dT%H:%M:%S.%f'
Definition at line 38 of file merge_function.py.