DESHIMA: dmerge_deprecated Namespace Reference
dmerge_deprecated Namespace Reference
Functions
def kids_with_both_blinds (kidslist, tod=None, allow_without_blind=False)
def read_kidslist (fname)
def read_localsweep (sweepfname, framelen)
Detailed Description
dmerge.pyの内、新しい関数やクラスに置き換えられ、テストのために消さずにおきたいものをこのファイルに記す。
(C) 2021 内藤システムズ
Function Documentation
kids_with_both_blinds()
def dmerge_deprecated.kids_with_both_blinds (kidslist, tod = None, allow_without_blind = False)
** bbsweeplib.TODcalibからコピー **
search kids its nearest blind tones.
kidslist :: a tuple of (info, kids, blinds, powers),
            that read_kidslist returns.
tod      :: None or a OrderedDict.
            if not None, only search KID in `tod`.
Return a list of list of form
  [[signal0, left0, right0],
   [signal1, left1, right1],
     :
     :
   [signalp, leftp, rightp]],
  where
    signalN : carrier bin number for KID,
    leftN   : carrier bin number for nearest left blind tone,
    rightN  : carrier bin number for nearest right blind tone,
  respectively.
  this list is sorted by bin number in lowest-first order.
Definition at line 6 of file dmerge_deprecated.py.
Referenced by test_dmerge.DmergeTestDrive.test_kids_with_both_blinds().
read_kidslist()
def dmerge_deprecated.read_kidslist (fname)
Read kidslist file. ** bbsweeplib.files.py **
Return (info, kids, blinds, powers)
  where info   is a dict with keys 'LO' (LO freq in Hz) and
                  framelen (frame count);
        kids   is a 1D list of bin indices for KIDs;
        blinds is a 1D list of bin indices for blind tones;
        powers is a OrderedDict, whose key is bin indices
                  and value is power for that bin.
Definition at line 67 of file dmerge_deprecated.py.
Referenced by test_dmerge.DmergeTestDrive.test_read_kidslist().
read_localsweep()
def dmerge_deprecated.read_localsweep (sweepfname, framelen)
Read local sweep file. ** bbsweeplib.files.py **
Returns a OrderedDict of md.SweepData's, keyed by bin number.
It is sorted by bin number, in lowest-first order.
Definition at line 120 of file dmerge_deprecated.py.
Referenced by test_dmerge.DmergeTestDrive.test_load_localsweep().