DESHIMA: make_reduced_fits Namespace Reference
make_reduced_fits Namespace Reference
Functions
def make_reduced_fits (kidfiles, output_filename)
Variables
args = sys.argv
cache_dir = args[1]
output_filename = args[2]
kidfiles = sorted(glob.glob(cache_dir + '/kid*.pkl'))
Detailed Description
フィットの結果からphaseなどを計算してfitsに格納する
Filename: make_reduced_fits.py
(C) 2021 内藤システムズ
使い方
------
このスクリプトは第一引数与えられたディレクトリの中のkidXXXXX.pklファイルをすべて読み込む。
各pklファイルにはフィットの結果が格納されていることが正常に動作するための前提条件となる。
解析結果をまとめて第二引数に与えられるファイル名で保存する。
例) カレントディレクトリにあるcacheディレクトリの中身をhoge.fitsへまとめる。
  $ python make_reduced_fits.py ./cache hoge.fits
Function Documentation
make_reduced_fits()
def make_reduced_fits.make_reduced_fits (kidfiles, output_filename)
Definition at line 25 of file make_reduced_fits.py.
References dmerge.calibrate_with_blind_tones(), dmerge.createBinTableHDU(), dmerge.find_glitch(), dmerge.gaolinbg_function(), dmerge.gaolinbg_rewind(), dmerge.interpolate_bad(), dmerge.kids_dict(), dmerge.readout_dict(), and dmerge.rebin_array().
Variable Documentation
args
make_reduced_fits.args = sys.argv
Definition at line 213 of file make_reduced_fits.py.
cache_dir
make_reduced_fits.cache_dir = args[1]
Definition at line 214 of file make_reduced_fits.py.
kidfiles
make_reduced_fits.kidfiles = sorted(glob.glob(cache_dir + '/kid*.pkl'))
Definition at line 216 of file make_reduced_fits.py.
output_filename
make_reduced_fits.output_filename = args[2]
Definition at line 215 of file make_reduced_fits.py.